const mockJobs = [
  {
    id: "1",
    is_bookmarked: false,
    title: "Warehouse Supervisor",
    major: "Logistics or Supply Chain Management",
    company: "Lazada Indonesia",
    location: "Depok, Jawa Barat",
    salary: "Rp. 6.000.000 - Rp. 9.000.000",
    category: "Supply Chain & Logistics",
    benefit:
      "health insurance, meal allowance, transportation allowance, performance bonus",
    rating: "4,2",
    listed: "4 days ago",
    job_category: "Full time",
    about_role:
      "As a Warehouse Supervisor at Lazada Indonesia, you will oversee daily warehouse operations, including inventory management, order fulfillment, and team coordination to ensure smooth logistics processes in our e-commerce fulfillment center.",
    job_desc: [
      "Supervise warehouse staff and coordinate daily operations",
      "Ensure accurate inventory management and timely order processing",
      "Implement and maintain safety and quality standards",
      "Monitor warehouse performance metrics and identify areas for improvement",
    ],
    requirements: [
      "Diploma or Bachelor's degree in Logistics, Supply Chain, or related field",
      "Minimum 3 years of experience in warehouse operations, with at least 1 year in supervisory role",
      "Knowledge of warehouse management systems and inventory control procedures",
      "Strong leadership and team management skills",
      "Problem-solving abilities and attention to detail",
      "Ability to work in shifts and handle physical aspects of the job",
    ],
    our_offer:
      "Lazada Indonesia offers a fast-paced environment with opportunities for career advancement in the growing e-commerce industry. We provide competitive salary, performance incentives, and comprehensive benefits package.",
  },
 
  {
    id: "2",
    is_bookmarked: false,
    title: "Engineer",
    major: "Industrial Engineer",
    company: "PT. Shimano Batam",
    location: "Batam Kota, Kepulauan Riau",
    salary: "Rp. 15.000.000 - Rp. 17.000.000",
    category: "Production, Manufacturing & Production",
    benefit: "career path, 5-Days work, salary negotiatable",
    rating: "5",
    listed: "3 hours ago",
    job_category: "Part Time",
    about_role:
      "As a Production Engineer Moulding at PT Ronstan International, you will play a crucial role in ensuring the smooth and efficient operation of the company's manufacturing processes. Based in Batam Riau Islands, this full-time position will see you responsible for overseeing and optimising the moulding production lines to meet the company's quality and output targets.",
    job_desc: [
      "Identify and implement process improvements to increase efficiency, productivity and cost-effectiveness",
      "Collaborate with the engineering and production teams to troubleshoot issues and find solutions",
      "Collaborate with the engineering and production teams to troubleshoot issues and find solutions",
      "Ensure adherence to all relevant safety, environmental and quality standards",
    ],
    requirements: [
      "Degree in Industrial Engineering or a related field",
      "Minimum 5 years' experience in a production engineering role, preferably in the manufacturing industry",
      "Strong problem-solving and analytical skills to identify and resolve production bottlenecks",
      "Proficient in the use of production management software and data analysis tools",
      "Excellent interpersonal and communication skills to liaise with cross-functional teams",
      "Ability to work well under pressure and meet tight deadlines",
      "Knowledge of lean manufacturing principles and continuous improvement methodologies",
    ],
    our_offer:
      "At PT Ronstan International, we are committed to providing a supportive and rewarding work environment for our employees. In addition to a competitive salary, we offer a range of benefits including health insurance, retirement planning, and opportunities for professional development and career advancement.",
  },


  {
    id: "3",
    is_bookmarked: false,
    title: "Software Engineer",
    major: "Computer Science",
    company: "Tokopedia",
    location: "Jakarta Selatan, DKI Jakarta",
    salary: "Rp. 12.000.000 - Rp. 18.000.000",
    category: "Information Technology & Software",
    benefit:
      "health insurance, flexible hours, annual bonus, remote work options",
    rating: "4.8",
    listed: "1 day ago",
    job_category: "Full time",
    about_role:
      "As a Software Engineer at Tokopedia, you'll be working on building and maintaining the company's e-commerce platform that serves millions of users across Indonesia. You'll join a dynamic team of engineers focused on developing scalable, reliable, and efficient solutions.",
    job_desc: [
      "Develop and maintain high-quality software applications",
      "Collaborate with cross-functional teams to define, design, and ship new features",
      "Optimize applications for maximum speed and scalability",
      "Write clean, maintainable code with proper documentation",
    ],
    requirements: [
      "Bachelor's degree in Computer Science, Engineering or related field",
      "At least 3 years of experience in software development",
      "Proficiency in one or more programming languages such as Go, Java, or Python",
      "Experience with microservices architecture",
      "Knowledge of database systems and cloud platforms",
      "Strong problem-solving skills and attention to detail",
    ],
    our_offer:
      "Tokopedia offers a competitive compensation package, health benefits, flexible working arrangements, and opportunities for professional growth. Join us in our mission to democratize commerce through technology!",
  },
  {
    id: "4",
    is_bookmarked: false,
    title: "Marketing Manager",
    major: "Marketing or Communications",
    company: "Unilever Indonesia",
    location: "Jakarta Pusat, DKI Jakarta",
    salary: "Rp. 15.000.000 - Rp. 25.000.000",
    category: "Marketing & Communications",
    benefit:
      "health benefits, performance bonus, paid leave, professional development",
    rating: "4.6",
    listed: "5 days ago",
    job_category: "Full time",
    about_role:
      "As a Marketing Manager at Unilever Indonesia, you will lead marketing initiatives for our consumer products, developing and implementing strategies that drive brand growth and market share in the competitive Indonesian market.",
    job_desc: [
      "Develop and execute marketing strategies for assigned product lines",
      "Analyze market trends and consumer insights to inform marketing decisions",
      "Manage marketing budget and evaluate ROI of campaigns",
      "Collaborate with agencies and internal teams on creative and media planning",
    ],
    requirements: [
      "Bachelor's degree in Marketing, Business, or related field",
      "Minimum 5 years of experience in consumer goods marketing",
      "Proven track record in leading successful marketing campaigns",
      "Strong analytical skills with ability to translate data into actionable insights",
      "Excellent project management and interpersonal skills",
      "Fluency in both Bahasa Indonesia and English",
    ],
    our_offer:
      "At Unilever, we offer competitive compensation, comprehensive benefits, and the opportunity to work with world-class brands. We foster a diverse and inclusive culture where you can make a real impact on the lives of consumers.",
  },
  {
    id: "5",
    is_bookmarked: false,
    title: "Financial Analyst",
    major: "Finance or Accounting",
    company: "Bank Central Asia (BCA)",
    location: "Jakarta Barat, DKI Jakarta",
    salary: "Rp. 8.000.000 - Rp. 12.000.000",
    category: "Finance & Banking",
    benefit: "health insurance, pension plan, annual bonus, training programs",
    rating: "4.5",
    listed: "2 days ago",
    job_category: "Full time",
    about_role:
      "As a Financial Analyst at BCA, you will be responsible for analyzing financial data, preparing reports, and providing recommendations to support strategic decision-making in one of Indonesia's largest banks.",
    job_desc: [
      "Analyze financial data and prepare regular financial reports",
      "Develop financial models and forecasts",
      "Monitor and analyze market trends and their financial implications",
      "Support budget planning and financial performance evaluation",
    ],
    requirements: [
      "Bachelor's degree in Finance, Accounting, or Economics",
      "Minimum 2 years of experience in financial analysis",
      "Proficiency in financial modeling and analysis tools",
      "Strong analytical skills and attention to detail",
      "Excellent communication skills",
      "Knowledge of banking regulations is a plus",
    ],
    our_offer:
      "BCA offers a stable work environment with excellent prospects for career advancement. We provide competitive remuneration, comprehensive benefits, and continuous professional development opportunities.",
  },
  {
    id: "6",
    is_bookmarked: false,
    title: "HR Specialist",
    major: "Human Resources Management",
    company: "Gojek",
    location: "Jakarta Selatan, DKI Jakarta",
    salary: "Rp. 7.000.000 - Rp. 10.000.000",
    category: "Human Resources",
    benefit:
      "health insurance, flexible working hours, meal allowance, transport allowance",
    rating: "4.9",
    listed: "Just now",
    job_category: "Full time",
    about_role:
      "As an HR Specialist at Gojek, you will support various HR functions to help maintain a positive work environment and ensure compliance with labor laws while supporting Gojek's rapid growth in the tech industry.",
    job_desc: [
      "Manage recruitment and onboarding processes",
      "Handle employee relations and address HR-related inquiries",
      "Maintain HR systems and employee records",
      "Support performance management and development programs",
    ],
    requirements: [
      "Bachelor's degree in Human Resources, Psychology, or related field",
      "Minimum 3 years of experience in HR roles",
      "Knowledge of Indonesian labor laws and regulations",
      "Strong interpersonal and communication skills",
      "Proficiency in HRIS and MS Office applications",
      "Experience in tech industry is a plus",
    ],
    our_offer:
      "Gojek offers a dynamic, fast-paced environment with the opportunity to make a real impact. We provide competitive salary, health benefits, and a unique culture that values innovation, collaboration, and personal growth.",
  },
  {
    id: "7",
    is_bookmarked: false,
    title: "Quality Control Inspector",
    major: "Engineering or Technical Field",
    company: "PT. Astra International",
    location: "Bekasi, Jawa Barat",
    salary: "Rp. 5.500.000 - Rp. 8.000.000",
    category: "Quality Assurance & Control",
    benefit:
      "health insurance, transportation allowance, meal allowance, shift allowance",
    rating: "4.3",
    listed: "1 week ago",
    job_category: "Full time",
    about_role:
      "As a Quality Control Inspector at PT. Astra International, you will be responsible for inspecting products and materials to ensure they meet quality standards before they leave the manufacturing facility.",
    job_desc: [
      "Inspect and test materials, products, and processes to ensure quality standards are met",
      "Document inspection results and maintain detailed records",
      "Identify quality issues and suggest improvements",
      "Collaborate with production teams to resolve quality problems",
    ],
    requirements: [
      "Diploma or Bachelor's degree in Engineering or related field",
      "Minimum 2 years of experience in quality control, preferably in automotive industry",
      "Knowledge of quality control methodologies and tools",
      "Familiarity with ISO standards and quality management systems",
      "Strong attention to detail and analytical skills",
      "Good communication skills",
    ],
    our_offer:
      "PT. Astra International offers a stable work environment with competitive compensation and benefits. We provide opportunities for skills development and career advancement within one of Indonesia's largest business groups.",
  },
  {
    id: "8",
    is_bookmarked: false,
    title: "Customer Service Representative",
    major: "Any Field",
    company: "Telkomsel",
    location: "Bandung, Jawa Barat",
    salary: "Rp. 4.500.000 - Rp. 6.000.000",
    category: "Customer Service & Support",
    benefit:
      "health insurance, communication allowance, performance incentives",
    rating: "4.4",
    listed: "2 days ago",
    job_category: "Full time",
    about_role:
      "As a Customer Service Representative at Telkomsel, you will be the first point of contact for our customers, providing assistance with services, addressing inquiries, and resolving issues to ensure high customer satisfaction.",
    job_desc: [
      "Handle customer inquiries via phone, email, and chat",
      "Process service applications, changes, and terminations",
      "Resolve customer complaints and follow up on pending issues",
      "Document all customer interactions in the CRM system",
    ],
    requirements: [
      "Minimum Diploma degree in any field",
      "At least 1 year of experience in customer service role",
      "Excellent communication skills in Bahasa Indonesia and basic English",
      "Patient and empathetic with strong problem-solving abilities",
      "Computer literacy and ability to learn new systems quickly",
      "Available to work in shifts including weekends and holidays",
    ],
    our_offer:
      "Telkomsel provides a dynamic work environment with continuous training and development. We offer competitive salary, health benefits, and performance incentives for dedicated team members who contribute to our customer satisfaction goals.",
  },
  {
    id: "9",
    is_bookmarked: false,
    title: "Graphic Designer",
    major: "Graphic Design or Visual Arts",
    company: "Bukalapak",
    location: "Jakarta Selatan, DKI Jakarta",
    salary: "Rp. 6.000.000 - Rp. 9.000.000",
    category: "Design & Creative",
    benefit:
      "health insurance, flexible work schedule, creative allowance, remote work options",
    rating: "4.7",
    listed: "3 days ago",
    job_category: "Full time",
    about_role:
      "As a Graphic Designer at Bukalapak, you will create engaging visual content for our e-commerce platform, marketing campaigns, and social media channels. Your creative work will help strengthen our brand identity and improve user experience.",
    job_desc: [
      "Design graphics for web, mobile applications, and marketing materials",
      "Create visually appealing content for social media and digital advertising",
      "Maintain brand consistency across all design projects",
      "Collaborate with marketing and product teams to understand design needs",
    ],
    requirements: [
      "Bachelor's degree in Graphic Design, Visual Arts, or related field",
      "Minimum 2 years of experience in graphic design, preferably in digital media",
      "Proficiency in Adobe Creative Suite (Photoshop, Illustrator, InDesign)",
      "Strong portfolio demonstrating creativity and design skills",
      "Understanding of UI/UX principles",
      "Ability to work in a fast-paced environment and meet deadlines",
    ],
    our_offer:
      "Bukalapak offers a creative and collaborative environment where your ideas will be valued. We provide competitive salary, comprehensive benefits, and the opportunity to work with one of Indonesia's leading tech companies.",
  },
  {
    id: "10",
    is_bookmarked: false,
    title: "Logistics Coordinator",
    major: "Supply Chain or Logistics Management",
    company: "JNE Express",
    location: "Tangerang, Banten",
    salary: "Rp. 5.000.000 - Rp. 7.500.000",
    category: "Supply Chain & Logistics",
    benefit:
      "health insurance, transport allowance, meal allowance, performance bonus",
    rating: "4.2",
    listed: "4 days ago",
    job_category: "Full time",
    about_role:
      "As a Logistics Coordinator at JNE Express, you will oversee daily logistics operations to ensure efficient movement of packages and deliveries. You will play a key role in maintaining service quality in one of Indonesia's leading courier companies.",
    job_desc: [
      "Coordinate and monitor daily shipment activities",
      "Track deliveries and resolve any logistical issues",
      "Maintain accurate records of shipments and inventories",
      "Liaise with drivers, warehouse staff, and customer service team",
    ],
    requirements: [
      "Diploma or Bachelor's degree in Logistics, Supply Chain Management or related field",
      "Minimum 2 years of experience in logistics or supply chain operations",
      "Knowledge of logistics processes and inventory management",
      "Strong organizational and problem-solving skills",
      "Proficiency in logistics management software",
      "Ability to work under pressure in a fast-paced environment",
    ],
    our_offer:
      "JNE Express offers a stable career in the growing logistics industry. We provide competitive compensation, health benefits, and opportunities for advancement as our company continues to expand nationwide.",
  },
  {
    id: "11",
    is_bookmarked: false,
    title: "Sales Executive",
    major: "Marketing or Business",
    company: "Property.com Indonesia",
    location: "Surabaya, Jawa Timur",
    salary: "Rp. 4.500.000 - Rp. 9.000.000",
    category: "Sales & Business Development",
    benefit:
      "high commission structure, transportation allowance, mobile phone allowance",
    rating: "4.1",
    listed: "1 week ago",
    job_category: "Full time",
    about_role:
      "As a Sales Executive at Property.com Indonesia, you will be responsible for acquiring new property listings and building relationships with real estate agents, developers, and property owners in Surabaya and surrounding areas.",
    job_desc: [
      "Identify and pursue new business opportunities in the real estate sector",
      "Build and maintain relationships with property owners, agents and developers",
      "Conduct presentations to showcase our platform's benefits",
      "Meet or exceed monthly sales targets",
    ],
    requirements: [
      "Bachelor's degree in Marketing, Business, or related field",
      "Minimum 1 year of experience in sales, preferably in real estate or digital services",
      "Strong negotiation and relationship-building skills",
      "Self-motivated with the ability to work independently",
      "Excellent communication skills in Bahasa Indonesia and English",
      "Valid driving license and willingness to travel within the region",
    ],
    our_offer:
      "Property.com offers an attractive base salary plus uncapped commission structure. We provide comprehensive training, supportive team environment, and clear paths for career advancement based on performance.",
  },
  {
    id: "12",
    is_bookmarked: false,
    title: "Mechanical Engineer",
    major: "Mechanical Engineering",
    company: "PT. Pertamina",
    location: "Balikpapan, Kalimantan Timur",
    salary: "Rp. 10.000.000 - Rp. 15.000.000",
    category: "Engineering",
    benefit:
      "housing allowance, health insurance, family benefits, education assistance",
    rating: "4,5",
    listed: "5 days ago",
    job_category: "Full time",
    about_role:
      "As a Mechanical Engineer at PT. Pertamina's Balikpapan Refinery, you will be involved in the design, installation, and maintenance of mechanical systems and equipment essential to our refining operations.",
    job_desc: [
      "Design and implement mechanical systems for refinery operations",
      "Oversee maintenance and repair of mechanical equipment",
      "Evaluate equipment performance and recommend improvements",
      "Ensure compliance with safety standards and regulations",
    ],
    requirements: [
      "Bachelor's degree in Mechanical Engineering",
      "Minimum 3 years of experience in industrial mechanical engineering, preferably in oil and gas industry",
      "Knowledge of mechanical design software and tools",
      "Understanding of industrial safety standards",
      "Strong analytical and problem-solving skills",
      "Willingness to travel to project sites across Eastern Indonesia",
    ],
    our_offer:
      "PT. Pertamina offers an excellent compensation package including relocation assistance for this position in Balikpapan. We provide comprehensive benefits, professional development opportunities, and the chance to work with Indonesia's leading energy company.",
  },
  {
    id: "13",
    is_bookmarked: false,
    title: "Restaurant Manager",
    major: "Hospitality Management",
    company: "Pizza Hut Indonesia",
    location: "Denpasar, Bali",
    salary: "Rp. 6.000.000 - Rp. 8.500.000",
    category: "Food & Beverage",
    benefit:
      "meal allowance, health insurance, performance bonus, staff discount",
    rating: "4,3",
    listed: "6 days ago",
    job_category: "Full time",
    about_role:
      "As a Restaurant Manager at Pizza Hut in Bali, you will oversee all aspects of restaurant operations, including staff management, customer service, food quality, and financial performance of the outlet.",
    job_desc: [
      "Manage daily restaurant operations and ensure high quality of food and service",
      "Recruit, train, and supervise restaurant staff",
      "Monitor inventory, control costs, and manage budgets",
      "Handle customer feedback and resolve issues promptly",
    ],
    requirements: [
      "Diploma or Bachelor's degree in Hospitality, Business, or related field",
      "Minimum 3 years of experience in restaurant or food service management",
      "Strong leadership and team management skills",
      "Understanding of food safety regulations and procedures",
      "Customer-focused mindset with excellent problem-solving abilities",
      "Ability to work in a fast-paced environment and flexible hours",
    ],
    our_offer:
      "Pizza Hut offers a dynamic work environment with opportunities for career advancement across our national network. We provide competitive salary, performance-based incentives, and comprehensive training programs to help you succeed in your role.",
  },
  {
    id: "14",
    is_bookmarked: false,
    title: "Content Writer",
    major: "Communications or Journalism",
    company: "Detik.com",
    location: "Jakarta Pusat, DKI Jakarta",
    salary: "Rp. 5.000.000 - Rp. 7.000.000",
    category: "Media & Communications",
    benefit: "health insurance, flexible hours, content creation training",
    rating: "4,4",
    listed: "1 day ago",
    job_category: "Full time",
    about_role:
      "As a Content Writer at Detik.com, you will create engaging, informative, and accurate news articles and feature stories across various topics for one of Indonesia's leading online news platforms.",
    job_desc: [
      "Research and write news articles, features, and special reports",
      "Follow current events and trending topics to produce timely content",
      "Conduct interviews and verify information from multiple sources",
      "Optimize content for digital platforms and social media",
    ],
    requirements: [
      "Bachelor's degree in Journalism, Communications, or related field",
      "Minimum 1 year of experience in content creation or journalism",
      "Excellent writing skills in Bahasa Indonesia with proper grammar and style",
      "Ability to work under tight deadlines and handle multiple assignments",
      "Strong research skills and attention to detail",
      "Basic understanding of SEO and digital content optimization",
    ],
    our_offer:
      "Detik.com offers a dynamic newsroom environment where you can develop your journalistic skills. We provide competitive compensation, health benefits, and the opportunity to work with experienced editors who will help advance your writing career.",
  },
  {
    id: "15",
    is_bookmarked: false,
    title: "Elementary School Teacher",
    major: "Education",
    company: "Sekolah Ciputra",
    location: "Surabaya, Jawa Timur",
    salary: "Rp. 5.000.000 - Rp. 8.000.000",
    category: "Education & Training",
    benefit:
      "education allowance, health insurance, annual bonus, holiday allowance",
    rating: "4,8",
    listed: "2 days ago",
    job_category: "Full time",
    about_role:
      "As an Elementary School Teacher at Sekolah Ciputra, you will be responsible for providing quality education to primary school students in a supportive and engaging learning environment following international curriculum standards.",
    job_desc: [
      "Plan and deliver lessons aligned with the school's curriculum and standards",
      "Assess and evaluate student performance and provide constructive feedback",
      "Create a positive learning environment that encourages student participation",
      "Communicate with parents regarding student progress and development",
    ],
    requirements: [
      "Bachelor's degree in Education or related field",
      "Teaching certification (required)",
      "Minimum 2 years of elementary teaching experience",
      "Knowledge of international curriculum (IB PYP preferred)",
      "Excellent communication skills in English and Bahasa Indonesia",
      "Patience, creativity, and genuine passion for working with children",
    ],
    our_offer:
      "Sekolah Ciputra offers a supportive professional environment with opportunities for professional development and career growth. We provide competitive salary, health benefits, and the chance to make a significant impact on students' educational journey.",
  },
  {
    id: "16",
    is_bookmarked: false,
    title: "Digital Marketing Specialist",
    major: "Marketing or Digital Communications",
    company: "Traveloka",
    location: "Jakarta Selatan, DKI Jakarta",
    salary: "Rp. 8.000.000 - Rp. 12.000.000",
    category: "Marketing & Communications",
    benefit:
      "health insurance, family medical coverage, annual bonus, travel benefits",
    rating: "4,6",
    listed: "Just now",
    job_category: "Full time",
    about_role:
      "As a Digital Marketing Specialist at Traveloka, you will plan and execute digital marketing campaigns across multiple channels to drive user acquisition, engagement, and retention for Southeast Asia's leading travel platform.",
    job_desc: [
      "Develop and implement digital marketing strategies across social media, email, and search platforms",
      "Analyze campaign performance and optimize based on ROI metrics",
      "Collaborate with creative teams to produce compelling marketing content",
      "Stay updated with digital marketing trends and best practices",
    ],
    requirements: [
      "Bachelor's degree in Marketing, Communications, or related field",
      "Minimum 3 years of experience in digital marketing roles",
      "Proven track record in managing successful digital campaigns",
      "Experience with digital analytics tools (Google Analytics, etc.)",
      "Knowledge of SEO, SEM, and social media marketing",
      "Strong analytical skills with data-driven decision making",
    ],
    our_offer:
      "Traveloka offers a dynamic environment where innovation is encouraged. We provide competitive compensation, comprehensive benefits including travel perks, and the opportunity to work with a team of passionate professionals reshaping the travel industry in Southeast Asia.",
  },
  {
    id: "17",
    is_bookmarked: false,
    title: "Production Operator",
    major: "High School",
    company: "PT. Shimano Batam",
    location: "Batam Kota, Kepulauan Riau",
    salary: "Rp. 5.000.000 - Rp. 7.000.000",
    category: "Production, Manufacturing & Production",
    benefit: "career path, 5-Days work, salary negotiatable",
    rating: "4.7",
    listed: "3 days ago",
    job_category: "Full time",
    about_role:
      "As a Production Engineer Moulding at PT Ronstan International, you will play a crucial role in ensuring the smooth and efficient operation of the company's manufacturing processes. Based in Batam Riau Islands, this full-time position will see you responsible for overseeing and optimising the moulding production lines to meet the company's quality and output targets.",
    job_desc: [
      "Identify and implement process improvements to increase efficiency, productivity and cost-effectiveness",
      "Collaborate with the engineering and production teams to troubleshoot issues and find solutions",
      "Collaborate with the engineering and production teams to troubleshoot issues and find solutions",
      "Ensure adherence to all relevant safety, environmental and quality standards",
    ],
    requirements: [
      "Degree in Industrial Engineering or a related field",
      "Minimum 5 years' experience in a production engineering role, preferably in the manufacturing industry",
      "Strong problem-solving and analytical skills to identify and resolve production bottlenecks",
      "Proficient in the use of production management software and data analysis tools",
      "Excellent interpersonal and communication skills to liaise with cross-functional teams",
      "Ability to work well under pressure and meet tight deadlines",
      "Knowledge of lean manufacturing principles and continuous improvement methodologies",
    ],
    our_offer:
      "At PT Ronstan International, we are committed to providing a supportive and rewarding work environment for our employees. In addition to a competitive salary, we offer a range of benefits including health insurance, retirement planning, and opportunities for professional development and career advancement.",
  },
  {
    id: "18",
    is_bookmarked: false,
    title: "Civil Engineer",
    major: "Civil Engineering",
    company: "PT. Wijaya Karya (WIKA)",
    location: "Makassar, Sulawesi Selatan",
    salary: "Rp. 8.000.000 - Rp. 12.000.000",
    category: "Construction & Engineering",
    benefit: "housing allowance, health insurance, project completion bonus",
    rating: "4,3",
    listed: "1 week ago",
    job_category: "Full time",
    about_role:
      "As a Civil Engineer at PT. Wijaya Karya, you will be involved in the planning, design, and execution of infrastructure projects in Eastern Indonesia, focusing on government-funded development initiatives in Sulawesi.",
    job_desc: [
      "Prepare engineering designs and technical specifications for construction projects",
      "Oversee construction activities and ensure compliance with plans and standards",
      "Coordinate with contractors, consultants, and government stakeholders",
      "Monitor project progress and prepare technical reports",
    ],
    requirements: [
      "Bachelor's degree in Civil Engineering",
      "Minimum 3 years of experience in infrastructure or building projects",
      "Knowledge of engineering design software (AutoCAD, etc.)",
      "Understanding of construction standards and building codes",
      "Strong analytical and problem-solving skills",
      "Willingness to travel to project sites across Eastern Indonesia",
    ],
    our_offer:
      "PT. Wijaya Karya offers a competitive salary package including project allowances and relocation assistance. We provide opportunities to work on significant national infrastructure projects and clear paths for career advancement in one of Indonesia's leading construction companies.",
  },
  {
    id: "19",
    is_bookmarked: false,
    title: "Nurse",
    major: "Nursing",
    company: "Siloam Hospitals",
    location: "Medan, Sumatera Utara",
    salary: "Rp. 4.500.000 - Rp. 7.000.000",
    category: "Healthcare & Medical",
    benefit: "health insurance, shift allowance, continuing education support",
    rating: "4,4",
    listed: "3 days ago",
    job_category: "Full time",
    about_role:
      "As a Nurse at Siloam Hospitals Medan, you will provide quality patient care as part of our healthcare team, contributing to our mission of delivering world-class healthcare services to the community in North Sumatra.",
    job_desc: [
      "Provide direct patient care according to nursing standards and hospital protocols",
      "Administer medications and treatments as prescribed by physicians",
      "Monitor patients' conditions and maintain accurate medical records",
      "Collaborate with doctors and other healthcare professionals",
    ],
    requirements: [
      "Diploma or Bachelor's degree in Nursing",
      "Valid STR (Surat Tanda Registrasi) and nursing license",
      "Minimum 1 year of clinical experience, preferably in hospital setting",
      "Knowledge of nursing procedures and medical terminology",
      "Good communication and interpersonal skills",
      "Willingness to work in shifts including nights and weekends",
    ],
    our_offer:
      "Siloam Hospitals offers a professional healthcare environment with continuous learning opportunities. We provide competitive compensation, comprehensive benefits package, and career advancement possibilities within our growing hospital network.",
  },
];

export default mockJobs;
